
package br.com.correios.bsb.sigep.master.bean.cliente;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.5
 * 2018-11-24T16:08:05.263-02:00
 * Generated source version: 3.2.5
 */

@WebFault(name = "Exception", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/")
public class Exception_Exception extends java.lang.Exception {

    private br.com.correios.bsb.sigep.master.bean.cliente.Exception exception;

    public Exception_Exception() {
        super();
    }

    public Exception_Exception(String message) {
        super(message);
    }

    public Exception_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, br.com.correios.bsb.sigep.master.bean.cliente.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, br.com.correios.bsb.sigep.master.bean.cliente.Exception exception, java.lang.Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public br.com.correios.bsb.sigep.master.bean.cliente.Exception getFaultInfo() {
        return this.exception;
    }
}
